In [1]:
import csv
import numpy as np
import pandas as pd

In [23]:
df1=pd.read_csv('/Users/yannangao/Desktop/segment3_workflow1.csv')

In [48]:
df2=pd.read_csv('/Users/yannangao/Desktop/segment3_W1.csv')

In [24]:
df1.head(10)

,Unnamed: 0,CASE_ID,WRKFLW_TSK_MAP_DETAILED
0,0,1067449|424909|657898,Submit
1,1,1067449|424909|657898,AR - Satisfied - Academic results for prior te...
2,2,1067449|424909|657898,AR - Not Satisfied - English language proficiency
3,3,1067449|424909|657898,OC - Created - English language requirements
4,4,1067449|424909|657898,AR - Created - Assessment information (Coursew...
5,5,1067449|424909|657898,Assessment Decision - Qualified
6,6,1067449|424909|657898,Send for Assessment
7,7,913640|554685|848410,Submit
8,8,913640|554685|848410,AR - Created - University of Melbourne Stateme...
9,9,913640|554685|848410,AR - Satisfied - University of Melbourne State...

In [49]:
df2.head(10)

,Unnamed: 0,CASE_ID,Submit,AR - Satisfied - Academic results for prior tertiary studies,AR - Created - Academic results for prior tertiary studies,AR - Created - Graduate Access Melbourne,AR - Created - Advanced standing application,AR - Created - Academic transcripts for prior tertiary studies,AR - Created - Academic transcript Grading Scheme,AR - Created - Academic transcripts statement of completion,AR - Created - Further information (1),Put Triage On-Hold,OC - Created - English language requirements,AR - Satisfied - Curriculum Vitae and professional experience,Assessment Decision - Qualified,AR - Created - Assessment information (Coursework) (1),AR - Satisfied - Further information (1),AR - Not Satisfied - English language proficiency,Release Triage Hold,Send for Assessment
0,0,1067449|424909|657898,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,913640|554685|848410,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2,1135096|528430|809259,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,3,1021374|367597|573577,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,4,1128107|501518|769785,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,5,1124743|501279|769447,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,6,1065704|422287|653985,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,7,760284|315130|499078,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,8,1153801|538391|823983,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,9,1121555|583498|885963,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
dict_1=df1.to_dict(orient='list')

In [28]:
case_id = dict_1['CASE_ID']

In [30]:
workflow = dict_1['WRKFLW_TSK_MAP_DETAILED']

In [31]:
print(type(workflow))
print(len(workflow))

<class 'list'>
5158

In [33]:
from collections import defaultdict

case_wf_dict = defaultdict(list)

for i in range(len(case_id)):
    item = case_id[i]
    case_wf_dict[item].append(workflow[i])
    
print(len(case_wf_dict))

752

In [34]:
case_wf_dict['1067449|424909|657898']

['Submit',
 'AR - Satisfied - Academic results for prior tertiary studies',
 'AR - Not Satisfied - English language proficiency',
 'OC - Created - English language requirements',
 'AR - Created - Assessment information (Coursework) (1)',
 'Assessment Decision - Qualified',
 'Send for Assessment']

In [50]:
df2 = df2.set_index('CASE_ID')

In [51]:
df2.head(5)

,Unnamed: 0,Submit,AR - Satisfied - Academic results for prior tertiary studies,AR - Created - Academic results for prior tertiary studies,AR - Created - Graduate Access Melbourne,AR - Created - Advanced standing application,AR - Created - Academic transcripts for prior tertiary studies,AR - Created - Academic transcript Grading Scheme,AR - Created - Academic transcripts statement of completion,AR - Created - Further information (1),Put Triage On-Hold,OC - Created - English language requirements,AR - Satisfied - Curriculum Vitae and professional experience,Assessment Decision - Qualified,AR - Created - Assessment information (Coursework) (1),AR - Satisfied - Further information (1),AR - Not Satisfied - English language proficiency,Release Triage Hold,Send for Assessment
CASE_ID,,,,,,,,,,,,,,,,,,,
1067449|424909|657898,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
913640|554685|848410,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1135096|528430|809259,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1021374|367597|573577,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1128107|501518|769785,4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [52]:
df2_col_name = df2.columns.values.tolist()
print(df2_col_name)

['Unnamed: 0', 'Submit', 'AR - Satisfied - Academic results for prior tertiary studies', 'AR - Created - Academic results for prior tertiary studies', 'AR - Created - Graduate Access Melbourne', 'AR - Created - Advanced standing application', 'AR - Created - Academic transcripts for prior tertiary studies', 'AR - Created - Academic transcript Grading Scheme', 'AR - Created - Academic transcripts statement of completion', 'AR - Created - Further information (1)', 'Put Triage On-Hold', 'OC - Created - English language requirements', 'AR - Satisfied - Curriculum Vitae and professional experience', 'Assessment Decision - Qualified', 'AR - Created - Assessment information (Coursework) (1)', 'AR - Satisfied - Further information (1)', 'AR - Not Satisfied - English language proficiency', 'Release Triage Hold', 'Send for Assessment']

In [53]:
for key in case_wf_dict.keys():
    for process in case_wf_dict[key]:
        if process in df2_col_name:
            df2.loc[key, process] = 1
        else:
            continue

In [54]:
df2.head()

,Unnamed: 0,Submit,AR - Satisfied - Academic results for prior tertiary studies,AR - Created - Academic results for prior tertiary studies,AR - Created - Graduate Access Melbourne,AR - Created - Advanced standing application,AR - Created - Academic transcripts for prior tertiary studies,AR - Created - Academic transcript Grading Scheme,AR - Created - Academic transcripts statement of completion,AR - Created - Further information (1),Put Triage On-Hold,OC - Created - English language requirements,AR - Satisfied - Curriculum Vitae and professional experience,Assessment Decision - Qualified,AR - Created - Assessment information (Coursework) (1),AR - Satisfied - Further information (1),AR - Not Satisfied - English language proficiency,Release Triage Hold,Send for Assessment
CASE_ID,,,,,,,,,,,,,,,,,,,
1067449|424909|657898,0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0
913640|554685|848410,1,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1135096|528430|809259,2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1021374|367597|573577,3,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1128107|501518|769785,4,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0

1.0